/**
 * Pure key generation functions for the storage layer.
 *
 * Why: The key schema is the heart of PolyGraph's index-free adjacency design.
 * These functions centralize all key format knowledge in one place, making it
 * impossible for the engine and adapter to disagree about key structure.
 *
 * Architecture: 90% pure functions / 10% I/O shell. This is the 90%.
 *
 * Key Schema:
 *   n:{nodeId}                        → Node data
 *   n:{nodeId}:l:{label}              → Label marker
 *   n:{nodeId}:o:{relType}:{relId}    → Outgoing adjacency
 *   n:{nodeId}:i:{relType}:{relId}    → Incoming adjacency
 *   r:{relId}                         → Relationship data
 *   i:l:{label}:{nodeId}              → Label index
 *   i:p:{label}:{prop}:{value}:{nodeId} → Property index
 *   m:{counter}                       → Metadata counter
 */

import type { NodeId, RelId } from '../types.js';

// ─── Node Keys ─────────────────────────────────────────────────────

/** Primary node storage key */
export function nodeKey(id: NodeId): string {
  return `n:${id}`;
}

/** Label marker on a node */
export function nodeLabelKey(id: NodeId, label: string): string {
  return `n:${id}:l:${label}`;
}

/** Outgoing adjacency marker: node → relationship */
export function nodeOutKey(id: NodeId, relType: string, relId: RelId): string {
  return `n:${id}:o:${relType}:${relId}`;
}

/** Incoming adjacency marker: relationship → node */
export function nodeInKey(id: NodeId, relType: string, relId: RelId): string {
  return `n:${id}:i:${relType}:${relId}`;
}

/** Prefix for scanning all outgoing adjacencies of a node */
export function nodeOutPrefix(id: NodeId): string {
  return `n:${id}:o:`;
}

/** Prefix for scanning outgoing adjacencies of a specific type */
export function nodeOutTypePrefix(id: NodeId, relType: string): string {
  return `n:${id}:o:${relType}:`;
}

/** Prefix for scanning all incoming adjacencies of a node */
export function nodeInPrefix(id: NodeId): string {
  return `n:${id}:i:`;
}

/** Prefix for scanning incoming adjacencies of a specific type */
export function nodeInTypePrefix(id: NodeId, relType: string): string {
  return `n:${id}:i:${relType}:`;
}

// ─── Relationship Keys ─────────────────────────────────────────────

/** Primary relationship storage key */
export function relKey(id: RelId): string {
  return `r:${id}`;
}

/** Prefix for scanning all relationships */
export function relPrefix(): string {
  return 'r:';
}

// ─── Index Keys ────────────────────────────────────────────────────

/** Label index: find all nodes with a given label */
export function labelIndexKey(label: string, nodeId: NodeId): string {
  return `i:l:${label}:${nodeId}`;
}

/** Prefix for scanning all nodes with a given label */
export function labelIndexPrefix(label: string): string {
  return `i:l:${label}:`;
}

/** Property index: find nodes by label + property value */
export function propIndexKey(label: string, propKey: string, value: any, nodeId: NodeId): string {
  return `i:p:${label}:${propKey}:${String(value)}:${nodeId}`;
}

/** Prefix for scanning a property index for a specific value */
export function propIndexValuePrefix(label: string, propKey: string, value: any): string {
  return `i:p:${label}:${propKey}:${String(value)}:`;
}

/** Prefix for scanning all entries of a property index */
export function propIndexPrefix(label: string, propKey: string): string {
  return `i:p:${label}:${propKey}:`;
}

// ─── Metadata Keys ─────────────────────────────────────────────────

export const COUNTER_NODE_COUNT = 'm:nodeCount';
export const COUNTER_REL_COUNT = 'm:relCount';

// ─── Key Parsing ───────────────────────────────────────────────────

/**
 * Extracts the last segment from a colon-delimited key.
 *
 * Why: Adjacency keys are `n:{nodeId}:o:{type}:{relId}` — the relId is
 * always last and is generated by `randomUUID()` (no colons), so this
 * is safe even when the nodeId or type contain colons.
 *
 * ⚠️ Do not use this to extract node ids from label-index keys; see
 * `labelIndexNodeId` for the colon-safe parser. The historical
 * assumption that "nodeIds don't contain colons" was wrong — callers
 * routinely use ids like `foundation/auth:createAuthProvider`.
 */
export function lastSegment(key: string): string {
  const parts = key.split(':');
  return parts[parts.length - 1];
}

/**
 * Strips a known prefix from a key. Use when the prefix length is
 * statically known; for keys with variable-length label/type segments
 * (label-index, property-index) use a dedicated parser instead
 * (`labelIndexNodeId` etc.).
 */
export function stripPrefix(key: string, prefix: string): string {
  return key.slice(prefix.length);
}

/**
 * Extracts the node id from a label-index key.
 *
 * Why: Label-index keys have the shape `i:l:{label}:{nodeId}`, and
 * node ids can contain colons (e.g. `foundation/auth:createAuthProvider`).
 * Splitting on `:` and taking the last segment silently dropped any
 * node whose id contained colons — see the 2026-05-12 parity-test
 * write-up for the surfaced symptom (`allNodes()` returning 955 of
 * 2113 nodes when loaded with constellation-style ids).
 *
 * The label itself is opaque (callers can pass arbitrary strings to
 * `createNode`), but the label-index prefix `i:l:` is fixed and the
 * label cannot itself contain a colon by today's writer conventions.
 * We strip the prefix, split off exactly one segment for the label,
 * and return everything after as the node id — colon-safe in the node
 * id and tolerant of any label without colons.
 *
 * Note: labels containing colons are *not* supported by this parser.
 * Today `createNode` accepts arbitrary label strings, so a label with
 * a colon would still corrupt the index. That is a separate, narrower
 * bug; tracking it as a TODO until a caller actually needs it.
 *
 * Returns `null` when the key does not match the label-index shape
 * (no `i:l:` prefix or no label/id separator).
 */
export function labelIndexNodeId(key: string): string | null {
  const prefix = 'i:l:';
  if (!key.startsWith(prefix)) return null;
  const rest = key.slice(prefix.length);
  const sep = rest.indexOf(':');
  if (sep < 0) return null;
  return rest.slice(sep + 1);
}
